# Generated by Django 5.1.5 on 2025-01-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Choice",
            new_name="Choice_1",
        ),
        migrations.RenameModel(
            old_name="Question",
            new_name="Question_1",
        ),
    ]
