# Generated by Django 5.1.5 on 2025-01-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_rename_choice_choice_1_rename_question_question_1"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Choice_1",
            new_name="Choice",
        ),
        migrations.RenameModel(
            old_name="Question_1",
            new_name="Question",
        ),
    ]
